---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: axonops-brokers
  namespace: ${KAFKA_NAMESPACE}
  labels:
    strimzi.io/cluster: ${STRIMZI_CLUSTER_NAME}
spec:
  replicas: ${STRIMZI_BROKER_REPLICAS}
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0 ## AxonOps requires there is a volume with index `0`
        type: persistent-claim
        size: ${STRIMZI_BROKER_STORAGE_SIZE}
        deleteClaim: false
        class: ${STRIMZI_BROKER_STORAGE_CLASS}
  template:
    kafkaContainer:
      env:
      - name: KAFKA_NODE_TYPE
        value: kraft-broker
      - name: AXON_AGENT_CLUSTER_NAME
        value: "${AXON_AGENT_CLUSTER_NAME}"
      - name: AXON_AGENT_ORG
        value: "${AXON_AGENT_ORG}"
      - name: AXON_AGENT_TLS_MODE
        value: "${AXON_AGENT_TLS_MODE}"
      - name: AXON_AGENT_SERVER_PORT
        value: "${AXON_AGENT_SERVER_PORT}"
      - name: AXON_AGENT_SERVER_HOST
        value: "${AXON_AGENT_SERVER_HOST}"
      - name: AXON_AGENT_KEY
        value: "${AXON_AGENT_KEY}"
