apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: axonops-k8ssandra-50
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: "5.0.6"
    serverImage: ${IMAGE_NAME:-ghcr.io/axonops/k8ssandra/cassandra:5.0.6-v0.1.110-1.0.0}
    softPodAntiAffinity: true
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 1Gi
    datacenters:
      - metadata:
          name: dc1
        size: 3
        # 1. Move 'env' inside a 'containers' block
        containers:
          - name: cassandra  # 2. Target the specific container
            env:             # 3. Use list format (name/value), not key:value map
              - name: AXON_AGENT_KEY
                value: "${AXON_AGENT_KEY}"
              - name: AXON_AGENT_ORG
                value: "${AXON_AGENT_ORG}"
              - name: AXON_AGENT_SERVER_HOST
                value: "${AXON_AGENT_SERVER_HOST}"
        config:
          jvmOptions:
            heap_initial_size: 1G
            heap_max_size: 1G
        storageConfig:
          cassandraDataVolumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
        # Add the extraVolumes section here
        extraVolumes:
          pvcs:
            - name: axonops-data
              mountPath: /var/lib/axonops
              pvcSpec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 512Mi
