name: 'AxonDB Search Extract Version'
description: 'Extracts OpenSearch and AxonOps versions from git tag (format: opensearch-VERSION or vdev-axondb-search-OPENSEARCH_VERSION-AXONOPS_VERSION)'
inputs:
  tag:
    description: 'Git tag to extract version from'
    required: true

outputs:
  opensearch_version:
    description: 'OpenSearch version (e.g., 3.3.2)'
    value: ${{ steps.extract.outputs.opensearch_version }}
  axonops_version:
    description: 'AxonOps version (e.g., 1.0.0)'
    value: ${{ steps.extract.outputs.axonops_version }}
  full_version:
    description: 'Full version string (e.g., 3.3.2-1.0.0)'
    value: ${{ steps.extract.outputs.full_version }}
  is_development:
    description: 'Whether this is a development release'
    value: ${{ steps.extract.outputs.is_development }}

runs:
  using: 'composite'
  steps:
    - name: Extract version components
      id: extract
      shell: bash
      run: |
        TAG="${{ inputs.tag }}"
        echo "Processing tag: $TAG"

        # Check if development tag (vdev-axondb-search-*)
        if [[ "$TAG" =~ ^vdev-axondb-search- ]]; then
          IS_DEV="true"
          # Remove vdev-axondb-search- prefix
          VERSION_STRING="${TAG#vdev-axondb-search-}"
        elif [[ "$TAG" =~ ^axondb-search- ]]; then
          IS_DEV="false"
          # Remove axondb-search- prefix
          VERSION_STRING="${TAG#axondb-search-}"
        else
          echo "ERROR: Tag does not match expected pattern (axondb-search-* or vdev-axondb-search-*)"
          exit 1
        fi

        echo "Version string: $VERSION_STRING"

        # Extract OpenSearch and AxonOps versions
        # Format: OPENSEARCH_VERSION-AXONOPS_VERSION (e.g., 3.3.2-1.0.0)
        if [[ "$VERSION_STRING" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          OPENSEARCH_VERSION="${BASH_REMATCH[1]}"
          AXONOPS_VERSION="${BASH_REMATCH[2]}"
        else
          echo "ERROR: Version string does not match OPENSEARCH_VERSION-AXONOPS_VERSION pattern"
          echo "Expected format: X.Y.Z-A.B.C (e.g., 3.3.2-1.0.0)"
          exit 1
        fi

        echo "OpenSearch version: $OPENSEARCH_VERSION"
        echo "AxonOps version: $AXONOPS_VERSION"
        echo "Is development: $IS_DEV"

        # Set outputs
        echo "opensearch_version=$OPENSEARCH_VERSION" >> $GITHUB_OUTPUT
        echo "axonops_version=$AXONOPS_VERSION" >> $GITHUB_OUTPUT
        echo "full_version=${OPENSEARCH_VERSION}-${AXONOPS_VERSION}" >> $GITHUB_OUTPUT
        echo "is_development=$IS_DEV" >> $GITHUB_OUTPUT

        echo "✓ Version extraction complete"
