name: 'AxonDB Search Backups Sign Container'
description: 'Signs container image with Sigstore Cosign using keyless signing'
inputs:
  image:
    description: 'Full image reference including digest (e.g., ghcr.io/axonops/axondb-search-backups@sha256:...)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign container image
      shell: bash
      run: |
        echo "Signing image: ${{ inputs.image }}"
        cosign sign --yes ${{ inputs.image }}
        echo "✓ Image signed successfully with Sigstore Cosign (keyless)"
