name: 'Setup BuildKit with Cache Persistence'
description: 'Sets up Docker Buildx with buildkit-cache-dance for persistent RUN --mount=type=cache mounts'
inputs:
  cache-map:
    description: 'JSON map of cache mount IDs to container paths (e.g., {"cqlai-rpms": "/var/cache/cqlai", "tini-binaries": "/var/cache/tini"})'
    required: true
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Restore BuildKit cache mounts from previous runs
      uses: reproducible-containers/buildkit-cache-dance@v3.1.2
      with:
        cache-map: ${{ inputs.cache-map }}
