apiVersion: v1
kind: Secret
metadata:
  name: axon-server-config
  namespace: axonops
type: Opaque
stringData:
  axon-server.yml: |
    agents_port: 1888
    api_port: 8080
    host: 0.0.0.0

    search_db:
      hosts:
        - https://axondb-search-cluster-master.axonops.svc.cluster.local:9200
      username: admin
      password: MySecureP4sswordHere@
      skip_verify: true

    org_name: example

    axon_dash_url: https://axonops.example.com

    log_file: /dev/stdout
    tls:
      mode: disabled
    auth:
      enabled: false
    cql_autocreate_tables: true
    cql_batch_size: 100
    cql_hosts:
    - axondb-timeseries-headless.axonops.svc.cluster.local
    # cql_keyspace_replication: '{ "class": "NetworkTopologyStrategy", "axonopsdb_dc1": 1 }'
    cql_local_dc: axonopsdb_dc1
    cql_max_searchqueriesparallelism: 100
    cql_metrics_cache_max_items: 500000
    cql_metrics_cache_max_size: 128
    cql_page_size: 100
    cql_proto_version: 4
    cql_reconnectionpolicy_initialinterval: 1s
    cql_reconnectionpolicy_maxinterval: 10s
    cql_reconnectionpolicy_maxretries: 10
    cql_retrypolicy_max: 10s
    cql_retrypolicy_min: 2s
    cql_retrypolicy_numretries: 3
    cql_skip_verify: true
    cql_ssl: true
    cql_username: axonops
    cql_password: MySecureP4sswordHere@
