---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-axon-config
  namespace: ${STRIMZI_NAMESPACE}
data:
  axon-agent.yml: |
    axon-server:
        hosts: "YOUR_AXONOPS_HOST"

    axon-agent:
        org: "YOUR_ORG_NAME"
        cluster_name: "YOUR_CLUSTER_NAME"
        key: "YOUR_AXONOPS_API_KEY"

    kafka:
      node_type: "connect"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: connect-cluster
  namespace: ${STRIMZI_NAMESPACE}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.1
  image: ghcr.io/axonops/strimzi/kafka:latest  # Replace with your AxonOps-enabled image
  replicas: 1
  bootstrapServers: ${STRIMZI_CLUSTER_NAME}-kafka-bootstrap:9092
  groupId: connect-group
  configStorageTopic: connect-configs
  statusStorageTopic: connect-status
  offsetStorageTopic: connect-offsets
  template:
    pod:
      volumes:
        - name: axon-agent-config-vol
          configMap:
            name: connect-axon-config
    connectContainer:
      volumeMounts:
        - name: axon-agent-config-vol
          mountPath: /mnt/
          readOnly: true
  config:
    # -1 means it will use the default replication factor configured in the connect
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
