---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: axonops-controller
  namespace: kafka
  labels:
    strimzi.io/cluster: axonops-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        class: ""
        kraftMetadata: shared
  template:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/name: axonops-kafka
    kafkaContainer:
      env:
      - name: KAFKA_NODE_TYPE
        value: kraft-broker
      - name: AXON_AGENT_CLUSTER_NAME
        value: "${AXON_AGENT_CLUSTER_NAME}"
      - name: AXON_AGENT_ORG
        value: "${AXON_AGENT_ORG}"
      - name: AXON_AGENT_TLS_MODE
        value: "${AXON_AGENT_TLS_MODE}"
      - name: AXON_AGENT_SERVER_PORT
        value: "${AXON_AGENT_SERVER_PORT}"
      - name: AXON_AGENT_SERVER_HOST
        value: "${AXON_AGENT_SERVER_HOST}"
      - name: AXON_AGENT_KEY
        value: "${AXON_AGENT_KEY}"
