---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: axonops-controller
  namespace: ${KAFKA_NAMESPACE}
  labels:
    strimzi.io/cluster: ${STRIMZI_CLUSTER_NAME}
spec:
  replicas: ${STRIMZI_CONTROLLER_REPLICAS}
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: ${STRIMZI_CONTROLLER_STORAGE_SIZE}
        deleteClaim: false
        class: ${STRIMZI_CONTROLLER_STORAGE_CLASS}
        kraftMetadata: shared
  template:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/name: ${STRIMZI_CLUSTER_NAME}
    kafkaContainer:
      env:
      - name: KAFKA_NODE_TYPE
        value: kraft-controller
      - name: AXON_AGENT_CLUSTER_NAME
        value: "${AXON_AGENT_CLUSTER_NAME}"
      - name: AXON_AGENT_ORG
        value: "${AXON_AGENT_ORG}"
      - name: AXON_AGENT_TLS_MODE
        value: "${AXON_AGENT_TLS_MODE}"
      - name: AXON_AGENT_SERVER_PORT
        value: "${AXON_AGENT_SERVER_PORT}"
      - name: AXON_AGENT_SERVER_HOST
        value: "${AXON_AGENT_SERVER_HOST}"
      - name: AXON_AGENT_KEY
        value: "${AXON_AGENT_KEY}"
