name: 'K8ssandra K3s Test cqlai'
description: 'Tests cqlai installation and CQL operations in Kubernetes pod'
inputs:
  pod_name:
    description: 'Name of the Cassandra pod'
    required: true
  namespace:
    description: 'Namespace of the pod'
    required: false
    default: 'k8ssandra-operator'
  username:
    description: 'Cassandra username (optional, defaults to cassandra)'
    required: false
    default: 'cassandra'
  password:
    description: 'Cassandra password (optional, defaults to cassandra)'
    required: false
    default: 'cassandra'

runs:
  using: 'composite'
  steps:
    - name: Verify cqlai is installed
      shell: bash
      run: |
        echo "Checking cqlai installation..."

        # Retry kubectl exec in case pod is transitioning
        RETRIES=0
        MAX_RETRIES=5
        while [ $RETRIES -lt $MAX_RETRIES ]; do
          if kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- cqlai --version 2>/dev/null; then
            echo "cqlai is installed"
            break
          fi

          RETRIES=$((RETRIES + 1))
          if [ $RETRIES -lt $MAX_RETRIES ]; then
            echo "kubectl exec failed, waiting 3s... (attempt $RETRIES/$MAX_RETRIES)"
            sleep 3
          else
            echo "ERROR: Failed to connect to pod after $MAX_RETRIES attempts"
            exit 1
          fi
        done

    - name: Test CQL operations with cqlai
      shell: bash
      run: |
        echo "=== Testing CQL operations with cqlai ==="

        echo "Creating keyspace..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "CREATE KEYSPACE IF NOT EXISTS cqlai_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"

        echo "Creating table..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "CREATE TABLE IF NOT EXISTS cqlai_test.users (id UUID PRIMARY KEY, name TEXT, email TEXT, created_at TIMESTAMP);"

        echo "Inserting test data..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "INSERT INTO cqlai_test.users (id, name, email, created_at) VALUES (uuid(), 'Alice', 'alice@example.com', toTimestamp(now()));"
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "INSERT INTO cqlai_test.users (id, name, email, created_at) VALUES (uuid(), 'Bob', 'bob@example.com', toTimestamp(now()));"
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "INSERT INTO cqlai_test.users (id, name, email, created_at) VALUES (uuid(), 'Charlie', 'charlie@example.com', toTimestamp(now()));"

        echo "Selecting data..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "SELECT * FROM cqlai_test.users;"

        echo "Verifying data..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "SELECT * FROM cqlai_test.users;" | grep -q "example.com"
        echo "Data verified"

        echo "Cleanup test keyspace..."
        kubectl exec -n ${{ inputs.namespace }} ${{ inputs.pod_name }} -c cassandra -- \
          cqlai -u ${{ inputs.username }} -p ${{ inputs.password }} -e "DROP KEYSPACE cqlai_test;"

        echo "=== All cqlai CQL tests passed ==="
