name: 'AxonOps Schema Registry Verify Published Image'
description: 'Verifies published image: signature, pull, start, healthcheck, and API smoke tests for a specific platform'
inputs:
  image:
    description: 'Full image reference with digest (e.g., ghcr.io/axonops/axonops-schema-registry@sha256:...)'
    required: true
  platform:
    description: 'Platform to pull and test (e.g., linux/amd64, linux/arm64)'
    required: false
    default: 'linux/amd64'
  container_name:
    description: 'Unique container name for this test run'
    required: false
    default: 'verify-test'
  port:
    description: 'Host port to map to container port 8081'
    required: false
    default: '8181'
  verify_signature:
    description: 'Whether to verify Cosign signature (set to false when calling multiple times to avoid redundant checks)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Cosign
      if: inputs.verify_signature == 'true'
      uses: sigstore/cosign-installer@v3

    - name: Verify image signature
      if: inputs.verify_signature == 'true'
      shell: bash
      run: |
        echo "=== Verifying Image Signature ==="
        echo "Image: ${{ inputs.image }}"

        cosign verify ${{ inputs.image }} \
          --certificate-identity-regexp="https://github.com/axonops/axonops-containers" \
          --certificate-oidc-issuer="https://token.actions.githubusercontent.com"

        echo "Image signature verified"

    - name: Pull image for ${{ inputs.platform }}
      shell: bash
      run: |
        echo "=== Pulling Image for ${{ inputs.platform }} ==="
        echo "Image: ${{ inputs.image }}"

        docker pull --platform ${{ inputs.platform }} ${{ inputs.image }}

        echo "Image pulled successfully for ${{ inputs.platform }}"

    - name: Start container (${{ inputs.platform }})
      shell: bash
      run: |
        echo "=== Starting container: ${{ inputs.container_name }} (${{ inputs.platform }}) ==="

        docker run -d --name ${{ inputs.container_name }} \
          --platform ${{ inputs.platform }} \
          --hostname ${{ inputs.container_name }} \
          -p ${{ inputs.port }}:8081 \
          ${{ inputs.image }}

        echo "Container started, waiting for Schema Registry..."

    - name: Wait for readiness (${{ inputs.platform }})
      shell: bash
      run: |
        echo "Waiting for Schema Registry using healthcheck.sh (startup probe)..."

        for i in {1..60}; do
          if docker exec ${{ inputs.container_name }} /usr/local/bin/healthcheck.sh startup > /dev/null 2>&1; then
            echo "Schema Registry startup complete (attempt $i, ~$((i*5)) seconds)"
            break
          fi
          if [ $((i % 6)) -eq 0 ]; then
            echo "Still waiting... attempt $i/60 (~$((i*5)) seconds elapsed)"
          fi
          sleep 5
        done

        # Final verification
        if ! docker exec ${{ inputs.container_name }} /usr/local/bin/healthcheck.sh startup; then
          echo "ERROR: Startup healthcheck failed after 5 minutes"
          docker logs ${{ inputs.container_name }} | tail -50
          exit 1
        fi

        echo "Startup probe passed"

    - name: Test healthcheck probes (${{ inputs.platform }})
      shell: bash
      run: |
        echo "=== Testing healthcheck probes (${{ inputs.platform }}) ==="

        echo "--- Startup probe ---"
        docker exec ${{ inputs.container_name }} /usr/local/bin/healthcheck.sh startup

        echo "--- Liveness probe ---"
        docker exec ${{ inputs.container_name }} /usr/local/bin/healthcheck.sh liveness

        echo "--- Readiness probe ---"
        docker exec ${{ inputs.container_name }} /usr/local/bin/healthcheck.sh readiness

        echo "All healthcheck probes passed"

    - name: Test Schema Registry API (${{ inputs.platform }})
      shell: bash
      run: |
        echo "=== Testing Schema Registry API (${{ inputs.platform }}) ==="

        HTTP_CODE=$(docker exec ${{ inputs.container_name }} curl -sf -o /dev/null -w "%{http_code}" http://localhost:8081/ 2>/dev/null || echo "000")

        if [ "$HTTP_CODE" = "200" ]; then
          echo "Health endpoint returned HTTP 200"
        else
          echo "ERROR: Health endpoint returned HTTP $HTTP_CODE"
          docker logs ${{ inputs.container_name }} | tail -20
          exit 1
        fi

        RESPONSE=$(docker exec ${{ inputs.container_name }} curl -sf http://localhost:8081/ 2>/dev/null || echo "FAILED")
        if [ "$RESPONSE" = "FAILED" ]; then
          echo "ERROR: Failed to get API response"
          exit 1
        fi

        echo "API response: $RESPONSE"
        echo "Schema Registry API test passed"

    - name: Verify architecture (${{ inputs.platform }})
      shell: bash
      run: |
        echo "=== Verifying architecture (${{ inputs.platform }}) ==="

        ARCH=$(docker exec ${{ inputs.container_name }} uname -m)
        echo "Container architecture: ${ARCH}"

        EXPECTED_ARCH=""
        if [[ "${{ inputs.platform }}" == *"amd64"* ]]; then
          EXPECTED_ARCH="x86_64"
        elif [[ "${{ inputs.platform }}" == *"arm64"* ]]; then
          EXPECTED_ARCH="aarch64"
        fi

        if [[ -n "$EXPECTED_ARCH" && "$ARCH" != "$EXPECTED_ARCH" ]]; then
          echo "ERROR: Expected ${EXPECTED_ARCH}, got ${ARCH}"
          exit 1
        fi

        echo "Architecture verified: ${ARCH}"

    - name: Cleanup (${{ inputs.platform }})
      if: always()
      shell: bash
      run: |
        echo "=== Cleanup: ${{ inputs.container_name }} ==="
        docker logs ${{ inputs.container_name }} 2>&1 | tail -20 || true
        docker stop ${{ inputs.container_name }} || true
        docker rm -f ${{ inputs.container_name }} || true
