name: 'AxonDB Time-Series Backups Verify Published Image'
description: 'Verifies backup container image was published to registry and signature is valid'
inputs:
  image:
    description: 'Full image reference (e.g., ghcr.io/axonops/development/axondb-timeseries-backups:1.3.0)'
    required: true
  image_digest:
    description: 'Image digest for signature verification (e.g., sha256:...)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Pull published image from GHCR
      shell: bash
      run: |
        echo "=== Pulling Published Image ==="
        echo "Image: ${{ inputs.image }}"
        docker pull ${{ inputs.image }}
        echo "✓ Image pulled from GHCR"

    - name: Verify Cosign signature
      shell: bash
      run: |
        echo "=== Verifying Image Signature ==="
        echo "Installing Cosign..."
        curl -sLO https://github.com/sigstore/cosign/releases/download/v2.2.0/cosign-linux-amd64
        chmod +x cosign-linux-amd64
        sudo mv cosign-linux-amd64 /usr/local/bin/cosign

        echo "Verifying signature for: ${{ inputs.image }}@${{ inputs.image_digest }}"
        cosign verify ${{ inputs.image }}@${{ inputs.image_digest }} \
          --certificate-identity-regexp="https://github.com/axonops/axonops-containers" \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com

        echo "✓ Signature verified"

    - name: Inspect image
      shell: bash
      run: |
        echo "=== Inspecting Image ==="
        docker inspect ${{ inputs.image }} | head -50
        echo "✓ Image inspection complete"

    - name: Verify backup scripts
      shell: bash
      run: |
        echo "=== Verifying Backup Scripts ==="

        # Test that backup script exists and is executable
        echo "Checking cassandra-remote-backup.sh..."
        docker run --rm --entrypoint /bin/sh ${{ inputs.image }} -c "test -x /usr/local/bin/cassandra-remote-backup.sh" || exit 1
        echo "✓ Backup script is present and executable"

        # Test that restore script exists and is executable
        echo "Checking cassandra-remote-restore.sh..."
        docker run --rm --entrypoint /bin/sh ${{ inputs.image }} -c "test -x /usr/local/bin/cassandra-remote-restore.sh" || exit 1
        echo "✓ Restore script is present and executable"

    - name: Verify rclone installation
      shell: bash
      run: |
        echo "=== Verifying rclone Installation ==="
        docker run --rm --entrypoint /bin/sh ${{ inputs.image }} -c "rclone version" || exit 1
        echo "✓ rclone is installed and working"

    - name: Verify user permissions
      shell: bash
      run: |
        echo "=== Verifying User Permissions ==="
        docker run --rm --entrypoint /bin/sh ${{ inputs.image }} -c "id cassandra | grep -q 'uid=999'" || exit 1
        echo "✓ Cassandra user permissions are correct"

    - name: Test script in TEST_MODE
      shell: bash
      run: |
        echo "=== Testing Script in TEST_MODE ==="
        # Run the backup script in TEST_MODE to verify it can start without AWS credentials
        docker run --rm -e TEST_MODE=true ${{ inputs.image }} || exit 1
        echo "✓ Script runs successfully in TEST_MODE"

    - name: Summary
      shell: bash
      run: |
        echo "================================================"
        echo "✓ Published Backup Image Verification Complete"
        echo "================================================"
        echo "Verified:"
        echo "  ✓ Image pulled from GHCR"
        echo "  ✓ Cosign signature valid"
        echo "  ✓ Backup and restore scripts present"
        echo "  ✓ rclone installed"
        echo "  ✓ User permissions correct"
        echo "  ✓ Script runs in TEST_MODE"
        echo "================================================"
        echo "Image: ${{ inputs.image }}"
        echo "Digest: ${{ inputs.image_digest }}"
        echo "================================================"
